import fs from 'fs';
import path from 'path';

import { DATA_RUNS_DIR, BACKEND_ROOT } from '../llm/utils/paths';

const TMP_DIR = path.join(BACKEND_ROOT, '.tmp');
const RUN_ID_FILE = path.join(TMP_DIR, 'vitest_run_id');

export const getTestRunDir = (dirName?: string): string => {
    let runId: string;

    if (dirName) {
        runId = dirName;
    } else {
        // Try to read the global run ID generated by global_setup.ts
        try {
            if (fs.existsSync(RUN_ID_FILE)) {
                runId = fs.readFileSync(RUN_ID_FILE, 'utf-8').trim();
            } else {
                // Fallback for isolated runs (e.g. running a single test file without global setup)
                runId = `test_run_latest`;
                console.warn(`[Utils] Global Run ID not found. Using fallback: ${runId}`);
            }
        } catch (error) {
            runId = `test_run_latest`;
            console.warn(`[Utils] Error reading Run ID. Using fallback: ${runId}`);
        }
    }

    const runDir = path.join(DATA_RUNS_DIR, runId);

    if (!fs.existsSync(runDir)) {
        fs.mkdirSync(runDir, { recursive: true });
        console.log(`[Utils] Created run directory: ${runDir}`);
    }

    return runDir;
};

export const getRunId = (): string => {
    if (fs.existsSync(RUN_ID_FILE)) {
        return fs.readFileSync(RUN_ID_FILE, 'utf-8').trim();
    }
    return "unknown_run_id";
}
